name: Rust

on:
  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update & Intall Packages
      run: sudo apt update --quiet --assume-yes && sudo apt upgrade --quiet --assume-yes && sudo apt install pkg-config libssl-dev --quiet --assume-yes 
    - name: Build
      run: cargo build --release
    - name: Clippy
      run: cargo clippy
