name: Rust

on:


  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update & Intall Packages
      run: sudo apt upgrade --quiet --assume-yes && sudo apt install pkg-config libssl-dev --quiet --assume-yes 
    - name: Build
      run: |
        cd back/search
        cargo build --release
    - name: Clippy
      run: |
        cd back/search
        cargo clippy
